import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import { ThemeProvider } from "./_components/theme-provider";
import Providers from "./_components/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html
        lang="en"
        suppressHydrationWarning
      >
        <body className={inter.className}>{children}</body>
        <Script
          src="https://sdk.scdn.co/spotify-player.js"
          strategy="afterInteractive"
        ></Script>
      </html>
    </Providers>
  );
}
